### ISSUE TITLE
Net::ReadTimeout: Net::ReadTimeout

### ISSUE THREAD

**Issue by akashgiricse** [hypertrack/hypertrack-ruby#3]
Please help, I'm getting "Net::ReadTimeout: Net::ReadTimeout" error again and again.
Here is the code I've written to get all users list
```
require 'hypertrack'
HyperTrack.secret_key = "sk_test_*****************************************"
HyperTrack.api_version = "v2"

HyperTrack::User.list
```

And here is the error I'm getting

```
Net::ReadTimeout: Net::ReadTimeout
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1407:in `request'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/hypertrack-0.2.2/lib/hypertrack/api_client.rb:78:in `block in make_request'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853:in `start'
/home/rango/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:584:in `start'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/hypertrack-0.2.2/lib/hypertrack/api_client.rb:69:in `make_request'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/hypertrack-0.2.2/lib/hypertrack/api_client.rb:35:in `fetch'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/hypertrack-0.2.2/lib/hypertrack/api_operations/common/list.rb:7:in `list'
<main>:4:in `<main>'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/lib/iruby/backend.rb:44:in `eval'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/lib/iruby/backend.rb:44:in `eval'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/lib/iruby/backend.rb:12:in `eval'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/lib/iruby/kernel.rb:87:in `execute_request'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/lib/iruby/kernel.rb:47:in `dispatch'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/lib/iruby/kernel.rb:37:in `run'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/lib/iruby/command.rb:70:in `run_kernel'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
/home/rango/.rvm/gems/ruby-2.4.1/bin/iruby:23:in `load'
/home/rango/.rvm/gems/ruby-2.4.1/bin/iruby:23:in `<main>'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/bin/ruby_executable_hooks:15:in `eval'
/home/rango/.rvm/gems/ruby-2.3.1@ruby2.3.1rails4.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

Although when I try to list all action throught the command 
`HyperTrack::Action.list`
it works fine. It outputs all the action list and realated data.

Any help would be greatly appreciated.

**Comment by guyzmo** [comment]
you can increase the time out with the env variable: `NET_TIMEOUT`, which defaults to 5, and rise it up to 20 or 30 (seconds that is).

**Comment by nileshtrivedi** [comment]
@akashgiricse It was a temporary issue with the backend and not really a bug in this Ruby library. Hence, closing.
